branch-defaults:
  master:
    environment: HackCovid-env
environment-defaults:
  HackCovid-env:
    branch: master
    repository: aws
global:
  application_name: hack-covid
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
